version: 0.2

phases:
  install:
    commands:
      - npm i
  build:
    commands:
      - npm test && npm run build
  post_build:
    commands:
      - npm run test-network
artifacts:
  files:
    - dist/**/*
    - node_modules
    - package-lock.json
    - package.json
    - ./*
